name: Simple Python CI

on: [push]

jobs:
  run-on-linux:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Run Hello World
      run: python hello.py
      
    - name: Create success file
      run: echo "Job completed at $(date)" > success.txt
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: linux-output
        path: success.txt

  run-on-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Run Hello World
      run: python hello.py
      
    - name: Create greeting file
      run: echo "Hello from Windows" > greeting.txt
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: windows-output
        path: greeting.txt

  run-locally:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Verify Python
      run: python --version
      
    - name: Run Hello World
      run: python hello.py
      
    - name: Create local info
      run: echo "Ran on local runner at $(date)" > local-info.txt
      
    - name: Upload local artifact
      uses: actions/upload-artifact@v3
      with:
        name: local-run
        path: local-info.txt
